name: ragverse
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.14
  - python=3.11.9
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - acres==0.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - amqp==5.2.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - attrs==23.2.0
      - babel==2.15.0
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.12.3
      - billiard==4.2.0
      - binaryornot==0.4.4
      - cachetools==5.3.3
      - celery==5.4.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - ci-info==0.3.0
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - colorama==0.4.6
      - configobj==5.0.9
      - configparser==7.1.0
      - cookiecutter==2.6.0
      - cryptography==42.0.8
      - cssselect==1.2.0
      - cssutils==2.11.1
      - dataclasses-json==0.6.7
      - deprecated==1.2.14
      - dirtyjson==1.0.8
      - diskcache==5.6.3
      - distlib==0.3.8
      - distro==1.9.0
      - dnspython==2.6.1
      - docopt==0.6.2
      - docutils==0.20.1
      - docx2txt==0.8
      - ecdsa==0.19.0
      - email-validator==2.1.2
      - emails==0.6
      - environs==9.5.0
      - etelemetry==0.3.1
      - fastapi==0.109.2
      - fastapi-cli==0.0.4
      - filelock==3.15.4
      - filetype==1.2.0
      - fitz==0.0.1.dev2
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - greenlet==3.0.3
      - grpcio==1.63.0
      - gunicorn==22.0.0
      - h11==0.14.0
      - hatch==1.12.0
      - hatchling==1.25.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.24.0
      - hyperlink==21.0.0
      - idna==3.7
      - imagesize==1.4.1
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.5
      - inboard==0.70.0
      - isodate==0.6.1
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jwt==1.3.1
      - keyring==25.2.1
      - kombu==5.3.7
      - llama-cloud==0.0.9
      - llama-cpp-python==0.2.78
      - llama-index==0.10.56
      - llama-index-agent-introspective==0.1.1
      - llama-index-agent-openai==0.2.9
      - llama-index-cli==0.1.12
      - llama-index-core==0.10.56
      - llama-index-embeddings-huggingface==0.2.2
      - llama-index-embeddings-openai==0.1.11
      - llama-index-indices-managed-llama-cloud==0.2.5
      - llama-index-legacy==0.9.48
      - llama-index-llms-groq==0.1.4
      - llama-index-llms-llama-cpp==0.1.4
      - llama-index-llms-ollama==0.1.4
      - llama-index-llms-openai==0.1.26
      - llama-index-llms-openai-like==0.1.3
      - llama-index-multi-modal-llms-openai==0.1.8
      - llama-index-program-openai==0.1.6
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.30
      - llama-index-readers-llama-parse==0.1.6
      - llama-index-storage-chat-store-redis==0.1.3
      - llama-index-vector-stores-milvus==0.1.20
      - llama-parse==0.4.9
      - looseversion==1.3.0
      - lxml==5.2.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - mdurl==0.1.2
      - milvus-lite==2.4.7
      - minijinja==2.0.1
      - more-itertools==10.3.0
      - morfessor==2.0.6
      - mosestokenizer==1.2.1
      - motor==3.5.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nibabel==5.3.2
      - nipype==1.9.1
      - nltk==3.9.1
      - numpy==1.26.4
      - odmantic==1.0.2
      - openai==1.36.0
      - openfile==0.0.7
      - packaging==24.1
      - pandas==2.2.2
      - passlib==1.7.4
      - pathlib==1.0.1
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==25.0.1
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - portalocker==2.8.2
      - premailer==3.10.0
      - prompt-toolkit==3.0.47
      - protobuf==5.27.2
      - prov==2.0.1
      - ptyprocess==0.7.0
      - puremagic==1.28
      - pyasn1==0.6.0
      - pycparser==2.22
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydantic-settings==2.2.1
      - pydot==3.0.2
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pymilvus==2.4.3
      - pymongo==4.7.3
      - pyparsing==3.2.0
      - pypdf==4.3.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-jose==3.3.0
      - python-multipart==0.0.9
      - python-slugify==8.0.4
      - pytz==2024.1
      - pyxnat==1.6.2
      - pyyaml==6.0.1
      - rdflib==6.3.2
      - redis==5.0.6
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - rsa==4.9
      - sacrebleu==2.4.2
      - sacremoses==0.1.1
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentence-transformers==3.0.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.7.1
      - setuptools==71.1.0
      - shellingham==1.5.4
      - simplejson==3.19.3
      - six==1.16.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==7.3.7
      - sphinx-argparse==0.4.0
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==2.0.31
      - starlette==0.36.3
      - striprtf==0.0.26
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.0
      - tomli-w==1.0.0
      - tomlkit==0.13.0
      - toolwrapper==2.1.0
      - torch==2.3.1
      - tqdm==4.66.4
      - traits==6.4.3
      - transformers==4.41.2
      - trove-classifiers==2024.7.2
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uctools==1.3.0
      - ujson==5.10.0
      - urllib3==2.2.2
      - userpath==1.9.2
      - uv==0.2.27
      - uvicorn==0.28.1
      - uvloop==0.19.0
      - vine==5.1.0
      - virtualenv==20.26.3
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - websockets==12.0
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.19.2
      - zstandard==0.23.0
